
package com.bonc.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DMDataServicePortType", targetNamespace = "http://service.business.nacao.ninemax.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DMDataServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "checkRDMInfo", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.CheckRDMInfo")
    @ResponseWrapper(localName = "checkRDMInfoResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.CheckRDMInfoResponse")
    public String checkRDMInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "resultFeedBackInfo", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.ResultFeedBackInfo")
    @ResponseWrapper(localName = "resultFeedBackInfoResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.ResultFeedBackInfoResponse")
    public String resultFeedBackInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "resultFeedBack", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.ResultFeedBack")
    @ResponseWrapper(localName = "resultFeedBackResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.ResultFeedBackResponse")
    public String resultFeedBack(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "monitorHealthy", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.MonitorHealthy")
    @ResponseWrapper(localName = "monitorHealthyResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.MonitorHealthyResponse")
    public String monitorHealthy(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "searchBGDMIInfo", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.SearchBGDMIInfo")
    @ResponseWrapper(localName = "searchBGDMIInfoResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.SearchBGDMIInfoResponse")
    public String searchBGDMIInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "searchDMInfo", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.SearchDMInfo")
    @ResponseWrapper(localName = "searchDMInfoResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.SearchDMInfoResponse")
    public String searchDMInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.business.nacao.ninemax.com")
    @RequestWrapper(localName = "checkDMInfo", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.CheckDMInfo")
    @ResponseWrapper(localName = "checkDMInfoResponse", targetNamespace = "http://service.business.nacao.ninemax.com", className = "com.bonc.ws.CheckDMInfoResponse")
    public String checkDMInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.business.nacao.ninemax.com")
        String in0);

}
