
package com.bonc.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DMDataService", targetNamespace = "http://service.business.nacao.ninemax.com", wsdlLocation = "file:/home/aiuap/SB_MDM_MDM_InquiryEnterpriseInfoSrv.wsdl")
public class DMDataService
    extends Service
{

    private final static URL DMDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException DMDATASERVICE_EXCEPTION;
    private final static QName DMDATASERVICE_QNAME = new QName("http://service.business.nacao.ninemax.com", "DMDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/aiuap/SB_MDM_MDM_InquiryEnterpriseInfoSrv.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DMDATASERVICE_WSDL_LOCATION = url;
        DMDATASERVICE_EXCEPTION = e;
    }

    public DMDataService() {
        super(__getWsdlLocation(), DMDATASERVICE_QNAME);
    }

    public DMDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DMDATASERVICE_QNAME, features);
    }

    public DMDataService(URL wsdlLocation) {
        super(wsdlLocation, DMDATASERVICE_QNAME);
    }

    public DMDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DMDATASERVICE_QNAME, features);
    }

    public DMDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DMDataServicePortType
     */
    @WebEndpoint(name = "DMDataServiceHttpPort")
    public DMDataServicePortType getDMDataServiceHttpPort() {
        return super.getPort(new QName("http://service.business.nacao.ninemax.com", "DMDataServiceHttpPort"), DMDataServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DMDataServicePortType
     */
    @WebEndpoint(name = "DMDataServiceHttpPort")
    public DMDataServicePortType getDMDataServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.business.nacao.ninemax.com", "DMDataServiceHttpPort"), DMDataServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DMDATASERVICE_EXCEPTION!= null) {
            throw DMDATASERVICE_EXCEPTION;
        }
        return DMDATASERVICE_WSDL_LOCATION;
    }

}
